### ISSUE TITLE
How to edit MWBScanner.js in Phonegap BUILD?

### ISSUE THREAD

**Issue by pieweb** [manateeworks/phonegap-mwbarcodescanner#11]
Currently scanner.startScanning() in MWBScanner.js takes no arguments, scan result is simply shown in an alert. 

How do edit MWBScanner.js in Phonegap BUILD so the result can be used?

Thank you

**Comment by manateeworks** [comment]
Custom callback and init function is added since version 1.4, so you can supply your own functions as arguments in scanner.startScanning. Please check notes inside MWBScanner.js related to version 1.4.

Regards
