### ISSUE TITLE
Phonegap Build and  Windows Phone

### ISSUE THREAD

**Issue by gustter** [manateeworks/phonegap-mwbarcodescanner#13]
Hello.

I'm trying out your library, so good, it's that I need. I have requested price for their site and I received it. All ok.

I'm using Phonegap Build. I compile without problem on iOS and Android. But  at Windows Phone I get the error: "Oh geez Your build failed Sorry, but a problem Occurred on the build server..".

If I remove &lt;gap: plugin name = &quot;com.manateeworks.barcodescanner&quot; /&gt; the error disappears, but obviously does not work.

Any ideas? Do you know about an issue with Phonegap Build and Windows Phone? It is important for us to run on all three platforms.

Thanks!

**Comment by cepm-nate** [comment]
I'm having the same issue. Here is the tail end of the log file.
```
Build FAILED.

"C:\project\MobileManagerv2.sln" (Rebuild target) (1) ->
"C:\project\MobileManagerv2.csproj" (Rebuild target) (2) ->
(ResolveAssemblyReferences target) -> 
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): error MSB3271: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture, "ARM", of the implementation file "C:\project\Plugins\com.manateeworks.barcodescanner\BarcodeLib.dll" for "C:\project\Plugins\com.manateeworks.barcodescanner\BarcodeLib.winmd". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and implementation file, or choose a winmd file with an implementation file that has a processor architecture which matches the targeted processor architecture of your project. [C:\project\MobileManagerv2.csproj]
```

**Comment by manateeworks** [comment]
Hello guys,

It's a known issue as online phonegap builder use 'Any CPU' as default configuration. Our decoder lib is written in C/C++ so it's not possible to get it working on that way - you can use it with ARM build configuration (which is impossible to select in online builder, you have to use offline one for that, open the project and change Any CPU to ARM).

Regards

**Comment by cepm-nate** [comment]
Interesting. So our choices are:

* We petition phonegap build to give us a 'CPU' option so we can select 'Any CPU' or 'ARM',
* We download phonegap and all the APKs to try and build everything locally (little tough for iOS on windows machines)
* We wait for you to release a library that will run on 'any CPU'.
* We use a different scanning engine.

**Comment by manateeworks** [comment]
Unfortunately there's no technical possibility to solve that form our side. MS is currently not providing a way to build C/C++ dll for 'Any CPU' configuration. If you can't build windows phone version locally i'm afraid you have no other solution but to use different scanning engine (which must be written in c#, so can't compete in performance with C/C++ decoder).
