### ISSUE TITLE
Gettin "*"

### ISSUE THREAD

**Issue by pugulino** [manateeworks/phonegap-mwbarcodescanner#14]
Hi.

First of all, thank you for sharing this plugin. It seems to be very powerful! However, when I try to scan a barcode, sometimes I get "asterisk" instead of the caracter.
For example, with this barcode
 <img src="http://www.barcodesinc.com/generator/image.php?code=Your%20Text&style=197&type=C128B&width=167&height=50&xres=1&font=3"/>
I always get "[asterisk]our [asterisk]ext". 

Do you guys have any idea why is this happening?
Thanks.

**Comment by manateeworks** [comment]
Hello,

Scanning any barcode utilizing the Manatee Works Barcode Scanner SDK without previously entering a valid license key will produce a result partially masked with asterisks (*).
The solution is to:
- Utilize our Evaluation License generator to generate a free 30-day trial license. After 30 days, the decoder will revert to its unlicensed state, and again partially mask results. If you wish to continue evaluating the SDK after 30 days, you may request a renewal of the evaluation keys by clicking the Renew button under each barcode type and completing a short Survey;
- Obtain a commercial license by requesting “Information & Pricing” from our home page.

Regards
