### ISSUE TITLE
Add License info

### ISSUE THREAD

**Issue by SunboX** [manateeworks/phonegap-mwbarcodescanner#15]
There's no information about including this plugin in commercial project. Please include a License.

**Comment by manateeworks** [comment]
Hello Sunbox,

Thanks for your interest in Manatee Works and our Barcode Scanner SDK. 

Note that if you decide to register for free on our Developer Network you'll get access to:

- Download our SDK;
- All available resources (documentation, news, blog posts, FAQ, etc);
- Our ticketing support system for technical inquiries;
- To our self-service for generating free evaluation licenses which last for an initial period of 30 days (and which will unmask the end result of a successful scan, allowing you to thoroughly evaluate our solution);
- Our Pricing info;
- Several promotional tools .. and more! 

As far as additional support services are concerned, you can check all available options on our Support page.
Feel free to let us know if there are any questions or concerns.

Best Regards

**Comment by SunboX** [comment]
Thanks for your quick reply. Would be nice if can add a "real" license file to this phonegap extension. By now it's not really clear if someone can or can't use this for free and under which terms.

Btw, the explanation of "symbols" is missing on your pricing page. And the other icons (in the other categories) are not really clear:

![symbology](https://cloud.githubusercontent.com/assets/83344/8225875/ce7dc7a6-1599-11e5-9849-d0008df82a30.PNG)

**Comment by manateeworks** [comment]
Hey SunboX. 

Which browser are you using? The issue that you described is not appearing on most browsers that we tested. The symbologies appear on the Comparison Chart just fine. 

Regards

**Comment by SunboX** [comment]
Firefox Dev Editon 40.0a1 ... upgraded to 40.0.a2 just now and can see the symbologies now. Don't know why this did happen. Thanks! :smile:

**Comment by manateeworks** [comment]
We're glad that your issue is resolved. Thanks for reporting it regardless. 

Regards

**Comment by eric-nodes** [comment]
Hi,
i would like to request more information on this plugin license : can we use it for free in commercial project or not ? Because although we did not have license key in our app, the scan is working.. so i'm a little bit confusing.. also your website says "FREE UPC AND EAN DECODING LICENSES" > so the decoding is free but not the scanner ?
I'm sorry, but i dont understand very well your model..
Thanks
Eric

**Comment by eric-nodes** [comment]
Ok, thanks for your answer
