### ISSUE TITLE
Add more and better examples

### ISSUE THREAD

**Issue by SunboX** [manateeworks/phonegap-mwbarcodescanner#16]
- How to get the response in a JavaScript callback instead of an `alert()`?
- How to config Barcode formats that should be recognized?
- Can we use the scanner in portrait mode?
- Can we change the scanner UI from JavaScript?
  - Grid Overlay
  - Icons
- The scanner may take long to startup, is there a "ready" event?

**Comment by manateeworks** [comment]
Hello Sunbox,

Most of these questions can be answered by looking at the comments in MWBScanner.js

    1.    The alert() is only an example of using the ‘result’ object in the response callback. The ‘result’ object provides the necessary information from the response and can be used for further actions. You can also use a separate file with custom callback and initialization function, like it’s described in readme file (section - Important change in 1.4).
    2.    Active codes can be set by using  mwbs['MWBsetActiveCodes'](constants.MWB_CODE_MASK_128 | constants.MWB_CODE_MASK_39); and adding the codes types you need.
    3.    Yes, it can be used in both orientations. Just uncomment     mwbs['MWBsetInterfaceOrientation'] (constants.OrientationPortrait); and set your desired orientation.
    4.    Overlay mode can be changed from JavaScript with the following options:
OverlayModeNone   - Show only camera preview
OverlayModeIMW    - Show the blinking lines and viewfinder rectangle
OverlayModeImage  - Show the provided image from the resource (overlay.png) which can be replaced with your custom image.
Icons can be changed only by replacing the native resource files
    5.    There is no such callback. Scanner usually needs about 1 second to initialize. If you are experiencing longer delays try to set fixed orientation inside AndroidManifest.xml for scanner activity (the same one you are using in mwbs['MWBsetInterfaceOrientation'] …)

Best Regards

**Comment by SunboX** [comment]
Thanks, that helps a bit more! :smile: I will try/evaluate these and maybe make a pull request for a README update containing better examples. :smirk:
