### ISSUE TITLE
How do i get the navigator.notification.prompt to pop up over the scanner?

### ISSUE THREAD

**Issue by johannady2** [manateeworks/phonegap-mwbarcodescanner#18]
I commented out finish(); in handleDecode function so it doesn't close the scanner when it scans something.. but I can't get the notification to appear on top of the scanner. I have to close the scanner to see it.

I want it to be like the manatee you can download in googleplay where the popup appears over the scanner.

I also plan to add a "quantity" input field since the user will be purchasing stuff. The app will be used in android and ios. Is it correct that I am using navigator.notification.prompt ? or should i be using something else?

**Comment by johannady2** [comment]
More details of what i'm trying to do:

http://stackoverflow.com/questions/31055128/how-to-overlap-navigator-notification-prompt-on-top-of-camera-in-cordova

**Comment by takinbo** [comment]
:+1:

I have the same problem as well.

**Comment by manateeworks** [comment]
There is no way of doing this with javascript and you'd have to code this natively.
