### ISSUE TITLE
Plugin not work on cordova platform windows

### ISSUE THREAD

**Issue by LucasNova** [manateeworks/phonegap-mwbarcodescanner#19]
Scanner don't work on windows(not WP8) platform? I has'nt any errors in terminal or crash application, just scanner not launch.

**Comment by SunboX** [comment]
jep, seems like `cordova platform add windows` is not supported by `mwbarcodescanner`. Would be nice if manateeworks could support windows universal, because wp8 support will be dropped by many companies soon.

**Comment by manateeworks** [comment]
Hello, 

We are currently working on the native windows universal app, for which we have plans to add it as phonegap plugin in the near future. We would love it if you guys can check it out once it becomes available as we will need all the feedback we can gather.

**Comment by SunboX** [comment]
Hi,

that's really great news! :smile: Can't await to try the new plugin, thanks for your work! :+1:

**Comment by manateeworks** [comment]
For anyone that would like to try our new UWP plugin, please contact dev@manateeworks.com.

Best,

Team Manatee
