### ISSUE TITLE
Update dependancies to use correct names

### ISSUE THREAD

**Issue by RYFN** [manateeworks/phonegap-mwbarcodescanner#20]
Update your dependancies to use the updated naming conventions, as per https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

This will resolve the following warnings on installation:

WARNING: org.apache.cordova.dialogs has been renamed to cordova-plugin-dialogs. You may not be getting the latest version! We suggest you `cordova plugin rm org.apache.cordova.dialogs` and `cordova plugin add cordova-plugin-dialogs`.

WARNING: org.apache.cordova.device has been renamed to cordova-plugin-device. You may not be getting the latest version! We suggest you `cordova plugin rm org.apache.cordova.device` and `cordova plugin add cordova-plugin-device`.

**Comment by manateeworks** [comment]
Thank you.
