### ISSUE TITLE
Partial screen scanning issue

### ISSUE THREAD

**Issue by eric-nodes** [manateeworks/phonegap-mwbarcodescanner#21]
Hi,
I have a strange issue with partial screen scanning : when the scan is initiated, the view does not show the camera but the scan is working, it seems that the background is overlayed, but the red cross is ok, and more strange : the scan works, i can retrieve barcode if i put a barcode behind the camera (even if i cant see the video output on the screen)..
Thanks for your help
Eric

**Comment by manateeworks** [comment]
Hello again Eric!

We've just submitted several fixes related to scanner performance in view. We will appreciate it very much if you can give it a go and see will it make any difference in regards to the issues that you've been experiencing. 

Looking forward to your feedback .

Regards

**Comment by eric-nodes** [comment]
Thanks again for your support! :-)

The fixes does not seem to change something unfortunately..

Regards
Eric

**Comment by manateeworks** [comment]
Eric, 

Can you share info about the exact device model and respective OS that you are working with so we can be in a position to pinpoint the issue?

Thanks in advance for your cooperation and willingless to assist.

Regards

**Comment by eric-nodes** [comment]
i'm working on nexus 5 with android 6.0 but this may come from my code because it was working just a few days ago

if i found something, i'll tell you

**Comment by eric-nodes** [comment]
Ok so more informations : 

- I started a new blank app
- I added manatee plugin > everything was fine, full and partial scan worked very well
- I made some tests on the config, still no pb
- I added crosswalk plugin > full scan OK ; partial scan does not work so i think the issue comes from crosswalk & manatee plugins compatibilities

**Comment by manateeworks** [comment]
Eric, 

Do you mind sending us your whole project with the crosswalk plugin included to support@manateeworks.com so we can troubleshoot the issue? Our tech team will be with you right away. 

Thanks in advance

**Comment by eric-nodes** [comment]
I will send you the test app, no problem.
Thanks

**Comment by chrisbeech** [comment]
Hello :) Any updates to the partial scanning issue re: crosswalk?

**Comment by eric-nodes** [comment]
Hello
No more information from Manatee, so i think it's not resolved

**Comment by manateeworks** [comment]
Hey guys, 

Unfortunately crosswalk seems conflicted with the camera preview within the current version. Other solutions have the same problem, so right now, the only we can do is wait for the next crosswall update and hope that they resolve it. 

Sorry that we do not have better news for you, but we'll revisit this first thing after a new crosswalk version is released. Once there's a breakdown, we'll update this thread. 

Thanks for your willingness to assist us through the troubleshooting. One can only hope for such a productive feedback.

**Comment by eric-nodes** [comment]
Thanks to you, for your work and for the monitoring.

**Comment by chrisbeech** [comment]
Thanks for your feedback and for the killer scanner component! Is there a specific JIRA issue for the camera preview you can point to? Would like to keep an eye on it https://crosswalk-project.org/jira/browse/XWALK?selectedTab=com.atlassian.jira.jira-projects-plugin:roadmap-panel&allVersions=true

**Comment by manateeworks** [comment]
Sorry... no. We will post an update here. 

Stay tuned!

**Comment by chrisbeech** [comment]
Hi Guys, the new version of crosswalk has become available: https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview any updates re: partial scanner?

**Comment by LucasNova** [comment]
Hi guys, i need place some html above the scanner rectangle, but scanner stay on higher level then webview. How can i make html under scanner, like a google-maps plugin for example. And if it possible, i can really easy and fast make my custom buttons and other scanner control elements.

**Comment by manateeworks** [comment]
Hey Lucas,

Unfortunately what are you trying to accomplish is not possible currently nor do we have plans to update the plugin in order for that to be achievable due to variety of reasons. 

In any case thanks for your feedback. If the situation changes, we'll let you know. 

Regards
The Manatee Works Support Team
Cognex Corporation
