### ISSUE TITLE
Cordova - Change Active codes after plugin is initialized

### ISSUE THREAD

**Issue by roarkmccolgan** [manateeworks/phonegap-mwbarcodescanner#23]
Hi There,

I am trying to use switches in my app to enable and disable barcodes on the fly, however I'm unable to reinitialize the plugin via MWBSInitSpace.init(); I get "dvc.platform is undefined"

How would I change the active barcodes and re-initialize the plugin?

Thanks!

**Comment by manateeworks** [comment]
Closing issue. Please revisit new repository: 

https://github.com/manateeworks/phonegap-manateeworks-v3
