### ISSUE TITLE
Stop scanning on non-partial view

### ISSUE THREAD

**Issue by denkomanceski** [manateeworks/phonegap-mwbarcodescanner#24]
I need to be able to close the scanner completly but I am using a non-partial (fullscreen) mode. How can I close the scanner programatically this way?

Thanks

**Comment by manateeworks** [comment]
Hello Denko, 

Thanks for contacting us and for using our PhoneGap Manatee Works Barcode Scanner SDK plugin. 

If you update your plugin to the latest available version (1.8.8), you will be able to close the scanner with the scanner.closeScanner(). 

Hopefully this will help you resolve your problem. 

Best Regards
The Manatee Works Team
Cognex Corporation
