### ISSUE TITLE
Asking for update

### ISSUE THREAD

**Issue by glowform** [manateeworks/phonegap-mwbarcodescanner#25]
When trying to build via build.phonegap.com for android I get this error:

Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: BarcodeScannerPlugin.java - You can fix this here

**Comment by manateeworks** [comment]
Hello!

In the latest version of our plugin (1.8.8) we added support for android app permissions which require using Cordova Android 5.0.0+. build.phonegap.com doesn’t yet support this Cordova Android version, so to avoid errors we recommend that you use version 1.8.7 of our plugin as it is the latest version that supports Cordova Android < 5.0.0.

Let us know if this will fix your issues. 

Best Regards
The Manatee Works Team
Cognex Corporation
