### ISSUE TITLE
Does not show full code after complete scanning 

### ISSUE THREAD

**Issue by sahidhossen** [manateeworks/phonegap-mwbarcodescanner#26]
When complete the scan result.code does not show full code. It show only 12 number but my code is 14 number. 

Can you solve this problem.

**Comment by manateeworks** [comment]
Hello! 

In order to be able to identify the issue we will need to see a sample of the code you are referring to. Can you provide it? 

Looking forward to hearing back from you. 

Best Regards
The Manatee Works Team
Cognex Corporation

**Comment by sahidhossen** [comment]
Here is my code . I am using angularjs. Code work fine for me but problem with the result. 

 MWBSInitSpace.callback = function(result){
           //console.log('MWBSInitSpace.callback Invoked at: '+ (new Date()).getTime());

            /**
              * result.code - string representation of barcode result
              * result.type - type of barcode detected or 'Cancel' if scanning is canceled
              * result.bytes - bytes array of raw barcode result
              * result.isGS1 - (boolean) barcode is GS1 compliant
              * result.location - contains rectangle points p1,p2,p3,p4 with the corresponding x,y
              * result.imageWidth - Width of the scanned image
              * result.imageHeight - Height of the scanned image
              */

            if(result.code){
                var code = result.code;
                $scope.barcodeResult = code;
//                            alert(result.code);
                 $http.post($scope.guest_url,
                 {
                     auth_token: $rootScope.authKey,
                     barcode: code.toString()
                 },
                 {
                     ignoreAuthModule: true
                 })
                 .success(function (data, status, headers, config) {
                    alert("yes");
                     if(data.message=="Success"){
                         $scope.barcodeResult="Success";
                     }else {
                         $scope.barcodeResult="Fail";
                     }
                    scanner.resumeScanning();
                 })
                 .error(function (data, status, headers, config) {
                     alert("Error occurred.  Status:" + status);
                     scanner.resumeScanning();
                 }).finally(function () {
                     $scope.loading = false;
                 });

            }
           console.log('Scan complete');
          if (result.type == 'Cancel'){
                   //Perform some action on scanning canceled if needed
                   }
                   else if (result && result.code){

                        setTimeout(function(){
                           scanner.resumeScanning();
                        },2000);

                      //navigator.notification.alert(result.code, function(){}, result.type + (result.isGS1?" (GS1)":""), 'Close');

                   }
          }

        $scope.$on('$ionicView.enter', function() {
             //$scope.scanBarcode();
            scanner.startScanning(MWBSInitSpace.init,MWBSInitSpace.callback, 20, 40, 60, 50);
        })

**Comment by manateeworks** [comment]
Hello again, 

We actually need a sample from the bar code, not the source code. Excuse me if I wasn't clear enough on that, even though the source code might prove useful. 

Looking forward to hearing back from you.

Best Regards
The Manatee Works Team
Cognex Corporation

**Comment by sahidhossen** [comment]
The result look like this: **032667010484 (problem with * sign)  
And the barcode is her. 
![attachment](https://cloud.githubusercontent.com/assets/12063077/15239552/45b544b0-1905-11e6-95e7-00b2cefc4ce1.png)

**Comment by manateeworks** [comment]
Hello, 

This is the answer to your inquiry: 

Scanning any barcode utilizing the Manatee Works Barcode Scanner SDK without previously entering a valid license key will produce a result partially masked with asterisks (*).The possible solutions are:

-Utilize our [Evaluation License generator](https://manateeworks.com/admin/support/licence/evaluate) to generate a free 30-day trial license. After 30 days, the decoder will revert to its unlicensed state, and again partially mask results. If you wish to continue evaluating the SDK after 30 days, you may request a renewal of the evaluation keys by clicking the Renew button under each barcode type and completing a short Survey;
- Obtain a commercial license by submitting a “[Purchase Request](https://manateeworks.com/admin/support/purchase/purchase_requests)” from the Purchase section of our [Developer Network](https://manateeworks.com/developers). 

Best Regards
The Manatee Works Team
Cognex Corporation
