### ISSUE TITLE
White background on Scan in view

### ISSUE THREAD

**Issue by zeddz92** [manateeworks/phonegap-mwbarcodescanner#27]
When i call scanner.startScanning(0,4,100,50) i get the frame and the scanner works, but i just see my app background, i would like to be able to see the camera in that frame.

**Comment by manateeworks** [comment]
Hello!

In order to be able to identify the issue can you provide more info, like on which devices are you testing, which phonegap version and as much additional details as you can?

Looking forward to hearing back from you.

Best Regards
The Manatee Works Team
Cognex Corporation

**Comment by zeddz92** [comment]
I'm using ionic 2, angular 2, cordova; 6.1.1 on galaxy s7 (android version: 6.0.1). This is what I get when I click on scan in view http://imgur.com/JZ7QORq.
Can't I get to see the camera on that frame instead of my app background?

**Comment by manateeworks** [comment]
Hello again, 

First of all sorry for the delayed response. Most of our team responsible for the Cordova plugin happened to be on a leave. 

At this point, we would suggest for you to first try and make sure that you have the latest Cordova plugin (1.8,8) available on our github page, which contains fixes that resolves most of the problems which were experienced by our Ionic users. If that doesn't help or if you already have the latest version installed, let us know and we'll take a look again. 

Looking forward to hearing back from you.

Best Regards
The Manatee Works Team
Cognex Corporation

**Comment by zeddz92** [comment]
No, i still get the same problem.

**Comment by manateeworks** [comment]
Hello,

Can we try couple of more things: 

1. Try your app on another Android device, from Samsung or other manufacturer
2. Can you send us the source code so we can check it out ourselves and see the problem first hand? We can't reproduce it currently. If its a problem to send the actual code of the app, you can make a new blank app with our plugin. 

Thanks in advance for your feedback and willingness to troubleshoot this issue. 

Looking forward to hearing back from you.

Best Regards
The Manatee Works Team
Cognex Corporation

**Comment by zeddz92** [comment]
nvm, i created a new project, installed plugin and it worked, you can close this issue, thanks.
