### ISSUE TITLE
Exception - Android build

### ISSUE THREAD

**Issue by graphefruit** [manateeworks/phonegap-mwbarcodescanner#28]
Try to build my android APK with the newest 1.9. version.
Error:

```
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:compileX86DebugNdk UP-TO-DATE
:compileX86DebugSources
:transformClassesWithDexForX86Debug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/manateeworks/BarcodeScanner$MWLocation;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
 FAILED
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

Picked up _JAVA_OPTIONS: -Xmx512M


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForX86Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\Java\jdk1.7.0_55\bin\java.exe'' finished with non-zero exit value 2

* Try:

BUILD FAILED

Total time: 1 mins 11.285 secs
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: Error code 1 for command: cmd with args: /s,/c,"C:\Users\user\Documents\test\platforms\android\gradlew cdvBuildDebug -b C:\Users\user\Documents\test\platforms\android\build.gradle -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"
```

With 1.8.1 everything worked fine.
This problems occures with the "crosswalk-plugin"-Installed to support older versions. 
The Crosswalk-Feature is a must need for us to work to support older versions.

Can you please help me @manateeworks?

**Comment by manateeworks** [comment]
Hello Grapefruit!

Recently, we made a change in the files organisation of our plugin, so a possible solution would be to remove the plugin, clean your project, and add the plugin again. Just remember to make a copy of MWBScanner.js or MWBConfig.js in order to save your scanner configuration.

Please try and let us know if that would solve your issue. 

Best regards
The Manatee Works Team
Cognex Corporation

**Comment by graphefruit** [comment]
Hello @manateeworks 
Tried it, still the same error.
Remove barcode, add crosswalk, add barcode. 
Had a look into the filesystem, the barcode plugin was removed, before I added crosswalk.

**Comment by graphefruit** [comment]
Any news @manateeworks  ?

**Comment by manateeworks** [comment]
Hello Grapefruit!

Please make sure that there is none of these files left anywhere in your project:
CameraManager.java
BarcodeScanner.java
MWOverlay.java

Let us know if that solves your issue.

Best regards
The Manatee Works Team
Cognex Corporation
