### ISSUE TITLE
Windows Phone - 10 - Scanner not working

### ISSUE THREAD

**Issue by graphefruit** [manateeworks/phonegap-mwbarcodescanner#30]
Hello @manateeworks 
The scanner is not working on windows phone 10 (.appx-files)

With an .XAP-File (8.1) everything works expected. The .APPX can be builded and is executed..
The "startScanning" method is available.
When I call "startScanning" the method: `BarcodeScanner.MWBinitDecoder(function(){`
is never triggered.

Plugin used: 1.8.7.
We need to deliver windows phone 10 aswell and have a valid licence.
On Android, IOS aswell on WP 8.1/10 (.XAP) everything works, but if using the .APPX (which is needed for WP10 because XAP makes problems, it doesn't work.

Thanks in advance
Graphefruit
PS: The camera was activated (front and rear) in the VS settings.

**Comment by manateeworks** [comment]
Hello again grapefruit, 

Unfortunately, currently, we do not support windows 10 on Cordova/Phonegap, but we are working on it as we speak and it will be available soon.

Thanks for your patience and understanding. 

Best Regards
The Manatee Works Team
Cognex Corporation

**Comment by graphefruit** [comment]
Hello @manateeworks,
do you have any timelines for this?
Available <= 1 Month, or more?
Thanks in advance
Graphefruit

**Comment by asinthecountry** [comment]
Hi @manateeworks 

Is there any update on a timeline for this?

We're already using your excellent plugin in our Android and iOS apps but we have a UWP app. We'd really like to move away from the phonegap-barcodescanner which is frankly pants on the Windows platform (various)!

**Comment by graphefruit** [comment]
Hello @manateeworks can you please give us an update about this process?

**Comment by manateeworks** [comment]
Hello everyone. Our UWP support for Cordova/PhoneGap is currently in beta. Please contact support@manateeworks.com if you would like a preview. We expect a full release in the next 2-3 weeks. 

Thank you for your patience.

Team Manatee
