### ISSUE TITLE
Cordova iOS build fails with fresh install

### ISSUE THREAD

**Issue by mindaboveall** [manateeworks/phonegap-mwbarcodescanner#31]
Undefined symbols for architecture armv7:
  "_kCLLocationAccuracyBest", referenced from:
      -[MWBAnalytics initializeAnalyticsWithUsername:apiKey:] in libBarcodeScanner.a(MWBAnalyticsIOS.o)
  "_kCLDistanceFilterNone", referenced from:
      -[MWBAnalytics initializeAnalyticsWithUsername:apiKey:] in libBarcodeScanner.a(MWBAnalyticsIOS.o)
  "_OBJC_CLASS_$_CLLocation", referenced from:
      objc-class-ref in libBarcodeScanner.a(MWBAnalyticsIOS.o)
  "_OBJC_CLASS_$_CLLocationManager", referenced from:
      objc-class-ref in libBarcodeScanner.a(MWBAnalyticsIOS.o)
  "_CLLocationCoordinate2DIsValid", referenced from:
      ___46-[MWBAnalytics MWA_sendReport:resultType:tag:]_block_invoke in libBarcodeScanner.a(MWBAnalyticsIOS.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

*\* BUILD FAILED **

**Comment by dhavaln** [comment]
@mindaboveall 
I think the npm is not updated, so do not install plugin via npm. Instead do this:
Take a clone of the repo locally and install with cordova plugin add <path of the plugin>

I have tested with `Xcode 7.3.1` and `iOS 9.3.2`

**Comment by kelvindart** [comment]
Thanks @dhavaln - this worked perfectly! Similarly, you can run:

`cordova plugin add https://github.com/manateeworks/phonegap-mwbarcodescanner`

Which installs the plugin from GitHub without having to locally clone the repo.
