### ISSUE TITLE
Android/iOS - Second scan problems

### ISSUE THREAD

**Issue by graphefruit** [manateeworks/phonegap-mwbarcodescanner#32]
Hello @manateeworks,
1. After one successfull scan inside my app, and another scan, I'm getting a "pause" symbol on the scan-overlay, instead the normal "cross", any ideas?
The scan is working completly normal, but user don't know where to point.
1. Also if you scan, the green successbox is shifted and not close to the realy scanned code. (Sorry the scan is to fast to provide an screenshot, just could mock it up)

![screenshot_20160713-102519](https://cloud.githubusercontent.com/assets/6260244/16796723/662c26f0-48e4-11e6-99e3-c21278cbe8ff.png)

The config:

```
    mwbs['MWBsetInterfaceOrientation'](constants.OrientationAll);
    mwbs['MWBenableHiRes'](true);
    mwbs['MWBenableFlash'](true);
    mwbs['MWBsetLevel'](3);
    mwbs['MWBsetDirection'](constants.MWB_SCANDIRECTION_VERTICAL | constants.MWB_SCANDIRECTION_HORIZONTAL);
    mwbs['MWBenableZoom'](true);
```

PS: I tried it with and without custom settings (same problem)
Thanks in advance
Graphefruit

**Comment by manateeworks** [comment]
Hello @graphefruit,

Could you please confirm that you are up to date with the latest version of our plugin and still getting the issue.

Best Regards

**Comment by graphefruit** [comment]
Hello @manateeworks,
thanks for your fast feedback.

I've updated to 1.9.1 -> The "pause" symbol error is gone, but the green-square box error is still existing, the barcode isn't fit rightly.

Also I'm getting now compile errors of your images:
:mergeArmv7DebugResourcesAAPT err(Facade for 6227031): C:\\platforms\android\res\drawable\flashbuttonoff.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(Facade for 31965127): C:\\platforms\android\res\drawable\zoom.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(Facade for 17902209): C:\\platforms\android\res\drawable\flashbuttonon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(Facade for 17902209): C:\\platforms\android\res\drawable\overlay_mw.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

That error didn't exist before.

**Comment by manateeworks** [comment]
Hello @graphefruit,

Those warnings shouldn't be a problem if they are not preventing you to build the app.

As for the green-square box it would be helpful if you tell us what device(s) are you using for testing and to describe how does the green-square box shift. Is it mirrored or is it always shifted on one side?

Best Regards

**Comment by graphefruit** [comment]
Hello @manateeworks,
heres a screen (I needed to destroy the barcode for reasons, aswell as the rest of the scan)
![scan_box](https://cloud.githubusercontent.com/assets/6260244/16806485/f4bf70f4-4914-11e6-8926-6750f34e5134.png)

Here you see the green circle placed to the right bottom of the barcode, which occures on all scans.

On iOS I cant see the green box (maybe the device is to fast).
On Android I see this box.

This problem occures on a HTC ONE M8 (Stock Vanilla, Android 6.0)
Aswell as on an very old phone Samsung Note 1 (Stock Samsung Rom, Android 4.1)

One Note 1 the box isn't moved that far like in the screenshot, but still not fitting.

Hopefully it helps
Best regards

**Comment by manateeworks** [comment]
Dear grapefruit, 

Since we need to ask a lot of questions and get into a more direct line of communication, would you mind contact us either through support@manateeworks.com or through the ticketing system of our [Developer Network](https://manateeworks.com/developers)?

Looking forward to hearing back from you. 

Best Regards
The Manatee Works Team
Cognex Corporation

**Comment by graphefruit** [comment]
Hello @manateeworks 
I just send an email.

Best Regards
Graphefruit
