### ISSUE TITLE
Edit on phonegap build

### ISSUE THREAD

**Issue by yohnan3396** [manateeworks/phonegap-mwbarcodescanner#33]
Hi,

On phonegap build, i need the function "scanner.startScanning()" write the barecode on an input and not an alert, how can i do ?
I'm french and don't understand all the documentation 
thanks for the help

**Comment by manateeworks** [comment]
Dear yohnan3396, 

We've tried to make the documentation as easy and as understandable as we can. Is there any particular section of it that you have troubles with?

Looking forward to hearing back from you.

Best Regards
The Manatee Works Team
Cognex Corporation

**Comment by yohnan3396** [comment]
It's easy to understand the documentation but i don't find the anwser of my question,

I installed the mwbarcodescanner on my PhoneGap build app. The scanner is amazing, congratulations. 

But, i need to change the function "scanner.startScanning", for the moment when i scan a barecode i got an alert with the barecode. 
Me, i need the barecode is written on an input and launch a JSON file.

Like that
`scanner.startscanning function .. {
Onsuccess 
{
$('#myinput').val("barecode.result");
.. call my json
}
OnError
{
alert('"error");
}
}`

Thanks for the help
Best regards

**Comment by manateeworks** [comment]
Dear yohnan3396, 

Thanks for your kind words. 

We're not sure that we understand your inquiry correctly but you might be able to achieve that by modifying the function “callFunc” in MWBScanner.js as it is the default scanner result callback. 

Let us know if that works for you. 

Best Regards
The Manatee Works Team
Cognex Corporation

**Comment by yohnan3396** [comment]
I can't modifying the function on PhoneGap Build, its the problem and i don't understand how call the function in my index.html
I see your change point 1.4, you say we can change the callback function if we include "js/MWBConfig.js" 
and launch the function on index.html

`    <button class="btn waves-effect waves-light deep-orange"  onclick="scanner.startScanning()" id="boutoninscription" type="button" name="action">Scanner un article
    <i class="material-icons right">send</i>
</button></center>
  <script type="text/javascript" src="js/MWBConfig.js"></script>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="MWBScanner.js"></script>
        <script type="text/javascript" src="datepicker.js"></script>
        <script type="text/javascript" src="js/connexion.js"></script>
       <script type="text/javascript">
scanner.startScanning = function(callback, options) {

how to launch the scanner and get the bar code ???


} `

**Comment by yohnan3396** [comment]
A question ,
I added the same file js/MWBConfig.js on my app and i call my scanner like that : 
onclick="scanner.startScanning(MWBSInitSpace.init,MWBSInitSpace.callback);" 
why the scanner doesnt work ? 

thanks

**Comment by manateeworks** [comment]
Dear yohnan3396,

Would you mind contacting our support directly through support@manateeworks.com? It would be much more convenient to establish a direct line of communication at this point in order to troubleshoot properly. 

Best Regards
The Manatee Works Team
Cognex Corporation

**Comment by yohnan3396** [comment]
Thanks, i send you an e-mail ;)

Regards

**Comment by aboveo** [comment]
even I didn't understand the documentation

how to get the scanned barcode to input text box rather than popping up an alert

**Comment by manateeworks** [comment]
Closing issue. Please revisit new repository: 

https://github.com/manateeworks/phonegap-manateeworks-v3
