### ISSUE TITLE
 How to add the license to prevent * in result?

### ISSUE THREAD

**Issue by kenvernaillenvub** [manateeworks/phonegap-mwbarcodescanner#35]

**Comment by manateeworks** [comment]
Hi kenvernaillenvub,

To set the license key for the Manatee Works Barcode Scanner, open the file MWBScanner.js located in www\plugins\manateeworks-barcodescanner\www of the startup project, and set
var ANDROID_KEY = 'androidKEY';
var IOS_KEY = 'iosKEY';

And the second place you have to change is open the file MWBConfig.js located in www\plugins\manateeworks-barcodescanner\js of the startup project, and set
var ANDROID_KEY = 'androidKEY';
var IOS_KEY = 'iosKEY';

Best regards,

Team Manatee
Cognex Corporation
