### ISSUE TITLE
Windows 10 - .appx - Support

### ISSUE THREAD

**Issue by graphefruit** [manateeworks/phonegap-mwbarcodescanner#36]
Hallo @manateeworks,

can you please tell me when Windows 10 is finally supported?
Thanks in advance
Graphefruit

**Comment by manateeworks** [comment]
Dear Grapefruit, 

We most certainly will. Just note that it might be a while until a stable version is released. 

Best Regards

**Comment by graphefruit** [comment]
Hello @manateeworks  
thanks for your feedback.
Can you please tell me a closer date? 
On 1. June you said there will be soon an version, now its mid september.
Thanks
Graphefruit

**Comment by manateeworks** [comment]
Unfortunately we can't tell you that it will be done at a specific date at this point, as much as we would like too. We're aware that it has been dragged on for a while because of the available resources, but we hope to resolve it. 

Best Regards

**Comment by graphefruit** [comment]
Hello @manateeworks,
thanks for this open feedback!
Best regards
Graphefruit

**Comment by graphefruit** [comment]
@manateeworks Update possible? 1 Month gone already

**Comment by manateeworks** [comment]
Sorry @graphefruit No progress yet.

**Comment by manateeworks** [comment]
Sorry @graphefruit No progress yet.

**Comment by graphefruit** [comment]
@manateeworks Can you please give me another eta on this? Our app works fine on android/ios, but wp 10 isn't working.

Its realy hard and limit our users on wp aswell.
Thanks
Graphefruit

**Comment by manateeworks** [comment]
Dear grapefruit, 

Unfortunately we can't share any ETA as we don't know when we will be done with this implementation. 

Please excuse us in advance with all the inconveniences causes. 

Best Regards

**Comment by manateeworks** [comment]
Hello everyone. Our UWP support for Cordova/PhoneGap is currently in beta. Please contact support@manateeworks.com if you would like a preview. We expect a full release in the next 2-3 weeks. 

Thank you for your patience.

Team Manatee
