### ISSUE TITLE
Nativescript support

### ISSUE THREAD

**Issue by denkomanceski** [manateeworks/phonegap-mwbarcodescanner#37]
Are there any plans to have nativescript support for these plugin? Since nativescript exposes the native APIs directly it should be very very easy to support this platform

Regards

**Comment by manateeworks** [comment]
Dear Denko, 

We have no plans to introduce nativescript support for our PhoneGap plugins at this time. We'll notify you if this changes in the future. 

Best Regards
Team Manatee
Cognex Corporation

**Comment by anto80** [comment]
any news for nativescript support

**Comment by manateeworks** [comment]
Hello,

Please contact sales@manateeworks.com. We would like to better understand your requirements.

Thanks
Team Manatee
Cognex Corporation
