### ISSUE TITLE
Build error on IOS platform 

### ISSUE THREAD

**Issue by sebastianor** [manateeworks/phonegap-mwbarcodescanner#38]
When I've removed old version of this plugin and install new version by:

> cordova plugin add https://github.com/manateeworks/phonegap-mwbarcodescanner

I can't build app on iOS because i've get error 

```
`   /app/platforms/ios/build/app.build/Debug-iphonesimulator/app.build/Objects-normal/x86_64/CDVMWBarcodeScanner.o
    /app/platforms/ios/build/app.build/Debug-iphonesimulator/app.build/Objects-normal/x86_64/MWOverlay.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
    Ld /app/platforms/ios/build/emulator/app.app/app normal x86_64
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/app/platforms/ios/cordova/build-debug.xcconfig,-project,app.xcodeproj,-target,app,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,build,CONFIGURATION_BUILD_DIR=/app/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/app/platforms/ios/build/sharedpch`
```

How resolve this problem ?

**Comment by manateeworks** [comment]
Dear sebastianor, 

Thanks for your inquiry. 

Please download the latest version of the plugin as there were some changes implemented lately and try again if the issue persists.  https://github.com/manateeworks/phonegap-mwbarcodescanner

Best Regards
Team Manatee 
Cognex Corporation

**Comment by cagedagain** [comment]
I'm also receiving this issue on installation.

**Comment by manateeworks** [comment]
Dear cagedagain,

Thanks for your inquiry.

Do you experience this issue with the latest version of the plugin? You can download it from the following page: https://github.com/manateeworks/phonegap-mwbarcodescanner

Best Regards
Team Manatee
Cognex Corporation

**Comment by cagedagain** [comment]
Yes - it's a fresh install on the latest version.

**Comment by manateeworks** [comment]
Cagedagain, Please open a [support ticket](https://manateeworks.com/admin/support/tickets/submit_ticket) within the Manatee Works [Developer Network](https://manateeworks.com/developers). We will be able to better serve you.
