### ISSUE TITLE
How to add the license to prevent * in result?

### ISSUE THREAD

**Issue by multilexus** [manateeworks/phonegap-mwbarcodescanner#39]
Hello,

I use the following code to call the scanner: "scanner.startScanning(MWBSInitSpace.init,$scope.scanCallbackManatee);"

I added MWBConfig.js and MWBScanner.js to my project. I generated a trial license and updated BOTH of these .js file with the trial license and it says Registration OK when I run the scanner, but it still has "*" in the result.

Any suggestions? Are MWBConfig.js and MWBScanner.js the only 2 files that need to include the license key?

P.S. I'm using it in my ionic/cordova application.

Thanks,
Alex $.

**Comment by manateeworks** [comment]
Dear Alex, 

Something must be wrong with your trial license. Can you submit a [support ticket](https://manateeworks.com/admin/support/tickets/ask) through the MWDN so our tech team can take a look directly?

Thanks in advance

**Comment by multilexus** [comment]
Hi, I did open a ticket over 24 hours ago. So far, no answer. Ticket number #754. 

The license key seems to be fine as it says "Registration OK", if I change any character in the license, I get Registration Invalid error. The trial license I'm using is only 2 days old.

**Comment by manateeworks** [comment]
Excuse us for the wait, our response time by default is 24-48 hours. We got a word that someone just posted a reply in your ticket. 

Hopefully your issue will soon be resolved. 

Best Regards

**Comment by multilexus** [comment]
Lesson learned: EAN & UPC are standard and do not require license, but will also work with DEFAULT trial license. For any other type of barcodes, click on EXPAND SYMBOLOGIES, and select specific barcode types that you need to decode. A custom trial license will be instantly generated based on specific barcode types. Any further changes in supported barcode type selection will generate a new trial license that works only for selected barcode types.
