### ISSUE TITLE
Scanned Text is incorrect

### ISSUE THREAD

**Issue by jeyaraman09** [manateeworks/phonegap-mwbarcodescanner#40]
Hi all,
please let me know this plugin is payable or free version.

I am using nodejs for creating cordova application.  
I want to scan Vehicle VIN Number(QR Code). I am using "manateeworks-barcodescanner 2.0.0" plugin 
for scanning, scanning was successful but scanned text was wrong, please find the Screen shot..

Please Help me

Thanks
V.Jeyaraman

![img_20161005_191958](https://cloud.githubusercontent.com/assets/19259069/19115941/74d2cfbc-8b31-11e6-80c4-fd9c19d6b145.jpg)

**Comment by manateeworks** [comment]
Hello V.Jeyaraman, 

Thank you for considering the Manatee Works Barcode Scanner SDK as your barcode scanning solution.

The barcode scanner is free only for UPC & EAN barcode symbologies. All other types of barcodes like QR or Code 39 (VIN), will require a commercial license purchase depending on your use-case. Costs and related terms can be found on our [Pricing](https://manateeworks.com/pricing) page. 

If the terms are acceptable for your business and when you decide on the right path to proceed forward, you simply need to register for the [Manatee Works Developer Network](https://manateeworks.com/developers) and submit a [License Purchase Request](https://manateeworks.com/admin/support/purchase/new_purchase_request?back=6358d8d). 
 
Feel free to let us know if there are any questions or concerns, and/or how we can assist you with the purchase of your Manatee Works Barcode Scanner SDK. We look forward to being part of your future.

Best regards,

Team Manatee
Cognex Corporation

**Comment by Dunman44** [comment]
Hi 
Having the same problem. I do have an account and lic keys.
In my MWBConfig.js file.
 var mwregister = {
            'Android': {
                'MWB_CODE_MASK_25': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_39': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_93': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_128': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_AZTEC': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_DM': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_EANUPC': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_PDF': { 'username': 'Myusername', 'key': 'MYKEy' },
                'MWB_CODE_MASK_QR': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_RSS': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_CODABAR': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_DOTCODE': { 'username': '', 'key': '' }
            },
            'iOS': {
                'MWB_CODE_MASK_25': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_39': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_93': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_128': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_AZTEC': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_DM': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_EANUPC': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_PDF': { 'username': 'Myusername', 'key': 'MyKey' },
                'MWB_CODE_MASK_QR': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_RSS': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_CODABAR': { 'username': '', 'key': '' },
                'MWB_CODE_MASK_DOTCODE': { 'username': '', 'key': '' }
            },
As far as i know you introduced a new major SDK V.3. The new license keys, including the trial license, will only work with the latest versions and the function on how to implement the license keys changed. But I cant find that new function.
Pls help

**Comment by manateeworks** [comment]
Hi Dunnman44,

To set the license key for the Manatee Works Barcode Scanner, open the file MWBScanner.js located in www\plugins\manateeworks-barcodescanner\www of the startup project, and set
var ANDROID_KEY = 'androidKEY';
var IOS_KEY     = 'iosKEY';

And the second place you have to change is open the file MWBConfig.js located in www\plugins\manateeworks-barcodescanner\js of the startup project, and set
var ANDROID_KEY = 'androidKEY';
var IOS_KEY     = 'iosKEY';

Best regards,

Team Manatee
Cognex Corporation
