### ISSUE TITLE
Android 7.1 - Scan flickers

### ISSUE THREAD

**Issue by graphefruit** [manateeworks/phonegap-mwbarcodescanner#42]
Hello @manateeworks, with Android 7.1 the scanner is flickering all the time.

I've installed the latest manatee-app.
Here's a short video demonstrating the problem: http://www.filedropper.com/vid20161025131724 

Greetings
Graphefruit

**Comment by manateeworks** [comment]
Dear Grapefruit, 

Thank you for reporting the issue. In order for us to investigate further, we need your input on the following: 

1. Which device are you using?
2. Can you reproduce the issue on our demo and our play store app?
3. Can you confirm that there is no similar issue with the system app? 

We look forward to your reply. 

Best Regards

**Comment by graphefruit** [comment]
Hello @manateeworks 

1. Pixel XL
2. I used your latest app from the app store.
3. The issue doesn't exist on my normal camera app.

For comparison: I installed 2 other barcode-apps, which doesn't have this problem.

Greetings
Graphefruit

**Comment by manateeworks** [comment]
@graphefruit We have been able to reproduce the issue. Thank you for bringing it to our attention. We will expedite a resolution. 

Regards,
Team Manatee

**Comment by graphefruit** [comment]
@manateeworks Any news here?

**Comment by manateeworks** [comment]
Hello. We believe the issue to be related to the camera driver. After updating your Pixel to the latest OS release, are you still experiencing the issue?

**Comment by graphefruit** [comment]
Yes still affected with latest updates

**Comment by manateeworks** [comment]
Closing issue. Please revisit new repository: 

https://github.com/manateeworks/phonegap-manateeworks-v3
