### ISSUE TITLE
Scanner is not working in Splitmode

### ISSUE THREAD

**Issue by graphefruit** [manateeworks/phonegap-mwbarcodescanner#43]
Hello @manateeworks,

with the new introduced splitview in Android 7.1 the manateeworks-scanner is not working.
I've added you two screenshots from your latest google-play app, once in splitmode, once normal.
You see the image very squeezed, scanning the barcode is impossible.

Phone: Google Pixel XL
Android: 7.1

![screenshot_20161129-161753](https://cloud.githubusercontent.com/assets/6260244/20715469/99f22b78-b64f-11e6-9dbd-a61a77a2800f.png)
![screenshot_20161129-161746](https://cloud.githubusercontent.com/assets/6260244/20715470/99f6a806-b64f-11e6-891a-8bff1ff95299.png)

**Comment by manateeworks** [comment]
Closing issue. Please revisit new repository: 

https://github.com/manateeworks/phonegap-manateeworks-v3
