### ISSUE TITLE
Unable to know settings CALLS

### ISSUE THREAD

**Issue by aboveo** [manateeworks/phonegap-mwbarcodescanner#45]
is there any document that explains settings calls

how do I rotate scanner to landscape by default

**Comment by manateeworks** [comment]
Hi,

The default orientation is Portrait, it can be changed in

mwbs['MWBsetInterfaceOrientation'] (constants.OrientationPortrait);

by changing the parameter to
  OrientationPortrait :         'Portrait',
  OrientationLandscapeLeft :    'LandscapeLeft',
  OrientationLandscapeRight :   'LandscapeRight'

Best Regards

**Comment by dody87** [comment]
Guys, could you put a simple example in the README.md It's really annoying and it's not faster. You're loosing possible users for that.

Thanks.

**Comment by manateeworks** [comment]
All examples are described inside mwbscanner.js as inline comments for every function.
