### ISSUE TITLE
scanner.scanImage() and scanner.startScanning() doesn't work in iOS 10

### ISSUE THREAD

**Issue by Hiroki1116** [manateeworks/phonegap-mwbarcodescanner#46]
The title says everything.
Both functions were fine in previous versions, but those functions crash the app as soon as any of them is called.

Does anyone have the same issue?

**Comment by manateeworks** [comment]
Have you confirmed the issue does not involved camera permissions?

Team Manatee
Cognex Corporation

**Comment by swcisel** [comment]
I'm able to run both just fine in iOS 10.2.1. Are you getting any useful messages when the app crashes?

**Comment by manateeworks** [comment]
Check info.plist for:

`<key>NSCameraUsageDescription</key>
    <string>Barcode Scanning</string>` 

It is required for iOS 10 +

Team Manatee
Cognex Corporation
