### ISSUE TITLE
Camera showing blank after enable the camera permission IPAD-IOS 10.2.1

### ISSUE THREAD

**Issue by kaviyarasu74** [manateeworks/phonegap-mwbarcodescanner#47]
Steps to reproduce

>>Install the app
>>Open the barcode scanner for first time
>>it will show pop up xxxx app would like to access Camera
>>Click ok
>>Blank screen appears-(no scanner/camera appears)
But once we close the application and reopen the app do the same steps it works

**Comment by manateeworks** [comment]
Duplicate: https://github.com/manateeworks/phonegap-manateeworks-v3/issues/6
