### ISSUE TITLE
unable to config in ionic v1 

### ISSUE THREAD

**Issue by Bala893** [manateeworks/phonegap-mwbarcodescanner#48]
Here my code myself using the ionic version1
i try to run this plugin in my app it does not happen any thing

can you please help me !

.controller('DashCtrl', function($scope,MWBarcodeScanner) {
$scope.scan = function(){
alert("test");
MWBarcodeScanner.startScanning().then(function(response){
console.log('show the result here');
console.log(response);
alert(response);
});
};
})

**Comment by manateeworks** [comment]
We only support the latest Ionic version 3.6.0, not previous versions.

You could still keep using v1 but we recommend you switch to the latest version, as the Ionic team make changes often, so the previous versions are removed from documentation and you're going to have a harder time developing.

Regards,
Team Manatee
