### ISSUE TITLE
After Scan BarCode shows *

### ISSUE THREAD

**Issue by Bala893** [manateeworks/phonegap-mwbarcodescanner#49]
If i scan barcode of type Code-128, bar code appends * to the code. How to resolve it?

![image](https://user-images.githubusercontent.com/22056977/28994079-cd6a479a-79e2-11e7-8393-9dc2778fe8dc.png)

![image](https://user-images.githubusercontent.com/22056977/28994082-e06addc8-79e2-11e7-82a6-864b5a4608e2.png)

**Comment by manateeworks** [comment]
Bala,

You are attempting to scan a barcode using an unlicensed version of our SDK. You may learn more from our [FAQ #1](https://manateeworks.com/frequently-asked-questions).

Regards,

Team Manatee
