### ISSUE TITLE
Scans once ok and on second scan pauses.

### ISSUE THREAD

**Issue by warrenbell** [manateeworks/phonegap-mwbarcodescanner#7]
Plugin scans once ok and pauses on second scan at:

[self.captureSession addInput:captureInput];

in MWScannerViewController.m

with a message of "Thread 1: EXC_BAD_ACCESS (code=1, address=0x...)

**Comment by manateeworks** [comment]
Hello warrenbell,

please try to update to the latest version of plugin to check is that issue resolved.

Regards
