### ISSUE TITLE
Where is version 1.4 ?

### ISSUE THREAD

**Issue by warrenbell** [manateeworks/phonegap-mwbarcodescanner#8]
Where is version 1.4 ? Installed via:

cordova plugin add https://github.com/manateeworks/phonegap-mwbarcodescanner.git

and I get version 1.3 ?

Thanks,

Warren Bell

**Comment by manateeworks** [comment]
Hello Bell

How are you checking the version? Inside MWBScanner.js file you should see 1.4 descriptions at the top of file.

Regards

**Comment by warrenbell** [comment]
cordova plugin list:

com.manateeworks.barcodescanner 1.3.0 "MWBarcodeScanner"

Your plugin.xml file says version 1.3. I now see the 1.4 where you stated.

Thanks,

Warren Bell

**Comment by manateeworks** [comment]
You'r right, we forgot to update the version in plugin.xml, thanks for notifying. But if you have 1.4 details in MWBScanner.js that means you are using the latest one.

Regards
