### ISSUE TITLE
Phonegap build Installation

### ISSUE THREAD

**Issue by SingleID** [manateeworks/phonegap-mwbarcodescanner#9]
I have followed your instructions for Windows Phone 8 and i have add this line on my config.xml

`<gap:plugin name="com.manateeworks.barcodescanner" version="1.4.1" />`

but when i click the button nothing happen.

Can you review/update the installation process for phonegap build ?
Thank you

**Comment by manateeworks** [comment]
Hello,

Recently we released a new version of our plugin so you can try it by using the updated instructions.

Regards

**Comment by SingleID** [comment]
The build for WM8 fail.

Here an abstract of the build log:

Required by "BarcodeLib".
      This reference is not "CopyLocal" because it's a prerequisite file.
      The ImageRuntimeVersion for this reference is "v4.0.30319".
  Dependency "System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
      Resolved file path is "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\WindowsPhone\v8.0\System.Runtime.InteropServices.WindowsRuntime.dll".
      Reference found at search path location "{TargetFrameworkDirectory}".
          For SearchPath "C:\project\Plugins\com.manateeworks.barcodescanner".
          Considered "C:\project\Plugins\com.manateeworks.barcodescanner\System.Runtime.InteropServices.WindowsRuntime.winmd", but it didn't exist.
          Considered "C:\project\Plugins\com.manateeworks.barcodescanner\System.Runtime.InteropServices.WindowsRuntime.dll", but it didn't exist.
          Considered "C:\project\Plugins\com.manateeworks.barcodescanner\System.Runtime.InteropServices.WindowsRuntime.exe", but it didn't exist.
          For SearchPath "{CandidateAssemblyFiles}".
          Considered "Plugins\com.manateeworks.barcodescanner\BarcodeLib.winmd", but its name "BarcodeLib" didn't match.
          Considered "Plugins\com.manateeworks.barcodescanner\BarcodeLib.dll", but its name "BarcodeLib" didn't match.
          Considered "Plugins\com.manateeworks.barcodescanner\WriteableBitmapExWinPhone.dll", but its name "WriteableBitmapExWinPhone" didn't match.
          Considered "Plugins\com.manateeworks.barcodescanner\WriteableBitmapExWinPhoneXnaDependant.dll", but its name "WriteableBitmapExWinPhoneXnaDependant" didn't match.
          For SearchPath "{TargetFrameworkDirectory}".
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\WindowsPhone\v8.0\System.Runtime.InteropServices.WindowsRuntime.winmd", but it didn't exist.
      Required by "BarcodeLib".
      This reference is not "CopyLocal" because it's a prerequisite file.
      The ImageRuntimeVersion for this reference is "v4.0.30319".
  Dependency "System.ObjectModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
      Resolved file path is "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\WindowsPhone\v8.0\System.ObjectModel.dll".
      Reference found at search path location "{TargetFrameworkDirectory}".
          For SearchPath "C:\project\Plugins\com.manateeworks.barcodescanner".
          Considered "C:\project\Plugins\com.manateeworks.barcodescanner\System.ObjectModel.winmd", but it didn't exist.
          Considered "C:\project\Plugins\com.manateeworks.barcodescanner\System.ObjectModel.dll", but it didn't exist.
          Considered "C:\project\Plugins\com.manateeworks.barcodescanner\System.ObjectModel.exe", but it didn't exist.
          For SearchPath "{CandidateAssemblyFiles}".
          Considered "Plugins\com.manateeworks.barcodescanner\BarcodeLib.winmd", but its name "BarcodeLib" didn't match.
          Considered "Plugins\com.manateeworks.barcodescanner\BarcodeLib.dll", but its name "BarcodeLib" didn't match.
          Considered "Plugins\com.manateeworks.barcodescanner\WriteableBitmapExWinPhone.dll", but its name "WriteableBitmapExWinPhone" didn't match.
          Considered "Plugins\com.manateeworks.barcodescanner\WriteableBitmapExWinPhoneXnaDependant.dll", but its name "WriteableBitmapExWinPhoneXnaDependant" didn't match.
          For SearchPath "{TargetFrameworkDirectory}".
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\WindowsPhone\v8.0\System.ObjectModel.winmd", but it didn't exist.
      Required by "BarcodeLib".
      This reference is not "CopyLocal" because it's a prerequisite file.
      The ImageRuntimeVersion for this reference is "v4.0.30319".
  Dependency "System.Runtime.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089".
      Resolved file path is "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\WindowsPhone\v8.0\System.Runtime.WindowsRuntime.dll".
      Reference found at search path location "{TargetFrameworkDirectory}".
          For SearchPath "C:\project\Plugins\com.manateeworks.barcodescanner".
          Considered "C:\project\Plugins\com.manateeworks.barcodescanner\System.Runtime.WindowsRuntime.winmd", but it didn't exist.
          Considered "C:\project\Plugins\com.manateeworks.barcodescanner\System.Runtime.WindowsRuntime.dll", but it didn't exist.
          Considered "C:\project\Plugins\com.manateeworks.barcodescanner\System.Runtime.WindowsRuntime.exe", but it didn't exist.
          For SearchPath "{CandidateAssemblyFiles}".
          Considered "Plugins\com.manateeworks.barcodescanner\BarcodeLib.winmd", but its name "BarcodeLib" didn't match.
          Considered "Plugins\com.manateeworks.barcodescanner\BarcodeLib.dll", but its name "BarcodeLib" didn't match.
          Considered "Plugins\com.manateeworks.barcodescanner\WriteableBitmapExWinPhone.dll", but its name "WriteableBitmapExWinPhone" didn't match.
          Considered "Plugins\com.manateeworks.barcodescanner\WriteableBitmapExWinPhoneXnaDependant.dll", but its name "WriteableBitmapExWinPhoneXnaDependant" didn't match.
          For SearchPath "{TargetFrameworkDirectory}".
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\WindowsPhone\v8.0\System.Runtime.WindowsRuntime.winmd", but it didn't exist.
      Required by "BarcodeLib".
      This reference is not "CopyLocal" because it's a prerequisite file.
      The ImageRuntimeVersion for this reference is "v4.0.30319".
  Dependency "System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089".
      Could not resolve this reference. Could not locate the assembly "System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
          For SearchPath "C:\project\Plugins\com.manateeworks.barcodescanner".
          Considered "C:\project\Plugins\com.manateeworks.barcodescanner\System.Runtime.WindowsRuntime.UI.Xaml.winmd", but it didn't exist.
          Considered "C:\project\Plugins\com.manateeworks.barcodescanner\System.Runtime.WindowsRuntime.UI.Xaml.dll", but it didn't exist.
          Considered "C:\project\Plugins\com.manateeworks.barcodescanner\System.Runtime.WindowsRuntime.UI.Xaml.exe", but it didn't exist.
          For SearchPath "{CandidateAssemblyFiles}".
          Considered "Plugins\com.manateeworks.barcodescanner\BarcodeLib.winmd", but its name "BarcodeLib" didn't match.
          Considered "Plugins\com.manateeworks.barcodescanner\BarcodeLib.dll", but its name "BarcodeLib" didn't match.
          Considered "Plugins\com.manateeworks.barcodescanner\WriteableBitmapExWinPhone.dll", but its name "WriteableBitmapExWinPhone" didn't match.
          Considered "Plugins\com.manateeworks.barcodescanner\WriteableBitmapExWinPhoneXnaDependant.dll", but its name "WriteableBitmapExWinPhoneXnaDependant" didn't match.
          For SearchPath "{TargetFrameworkDirectory}".
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\WindowsPhone\v8.0\System.Runtime.WindowsRuntime.UI.Xaml.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\WindowsPhone\v8.0\System.Runtime.WindowsRuntime.UI.Xaml.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\WindowsPhone\v8.0\System.Runtime.WindowsRuntime.UI.Xaml.exe", but it didn't exist.
          For SearchPath "C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\Windows Phone\v8.0\Libraries\".
          Considered "C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\Windows Phone\v8.0\Libraries\System.Runtime.WindowsRuntime.UI.Xaml.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\Windows Phone\v8.0\Libraries\System.Runtime.WindowsRuntime.UI.Xaml.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\Windows Phone\v8.0\Libraries\System.Runtime.WindowsRuntime.UI.Xaml.exe", but it didn't exist.
          For SearchPath "C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v8.0\Libraries\".
          Considered "C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v8.0\Libraries\System.Runtime.WindowsRuntime.UI.Xaml.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v8.0\Libraries\System.Runtime.WindowsRuntime.UI.Xaml.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v8.0\Libraries\System.Runtime.WindowsRuntime.UI.Xaml.exe", but it didn't exist.
          For SearchPath "C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v8.0\ExtensionSDKs\MSAdvertising\6.1\References\CommonConfiguration\neutral\".
          Considered "C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v8.0\ExtensionSDKs\MSAdvertising\6.1\References\CommonConfiguration\neutral\System.Runtime.WindowsRuntime.UI.Xaml.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v8.0\ExtensionSDKs\MSAdvertising\6.1\References\CommonConfiguration\neutral\System.Runtime.WindowsRuntime.UI.Xaml.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v8.0\ExtensionSDKs\MSAdvertising\6.1\References\CommonConfiguration\neutral\System.Runtime.WindowsRuntime.UI.Xaml.exe", but it didn't exist.
          For SearchPath "C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\Windows Phone\v7.1\Libraries\".
          Considered "C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\Windows Phone\v7.1\Libraries\System.Runtime.WindowsRuntime.UI.Xaml.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\Windows Phone\v7.1\Libraries\System.Runtime.WindowsRuntime.UI.Xaml.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\Windows Phone\v7.1\Libraries\System.Runtime.WindowsRuntime.UI.Xaml.exe", but it didn't exist.
          For SearchPath "C:\Program Files (x86)\Microsoft SDKs\Expression\Extensions\FXG\Libraries\Windows Phone\v7.0\".
          Considered "C:\Program Files (x86)\Microsoft SDKs\Expression\Extensions\FXG\Libraries\Windows Phone\v7.0\System.Runtime.WindowsRuntime.UI.Xaml.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SDKs\Expression\Extensions\FXG\Libraries\Windows Phone\v7.0\System.Runtime.WindowsRuntime.UI.Xaml.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SDKs\Expression\Extensions\FXG\Libraries\Windows Phone\v7.0\System.Runtime.WindowsRuntime.UI.Xaml.exe", but it didn't exist.
          For SearchPath "C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v7.1\Libraries\Silverlight\".
          Considered "C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v7.1\Libraries\Silverlight\System.Runtime.WindowsRuntime.UI.Xaml.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v7.1\Libraries\Silverlight\System.Runtime.WindowsRuntime.UI.Xaml.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v7.1\Libraries\Silverlight\System.Runtime.WindowsRuntime.UI.Xaml.exe", but it didn't exist.
          For SearchPath "C:\Program Files (x86)\Microsoft SDKs\Advertising for Phone\Libraries\v7.1\".
          Considered "C:\Program Files (x86)\Microsoft SDKs\Advertising for Phone\Libraries\v7.1\System.Runtime.WindowsRuntime.UI.Xaml.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SDKs\Advertising for Phone\Libraries\v7.1\System.Runtime.WindowsRuntime.UI.Xaml.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Microsoft SDKs\Advertising for Phone\Libraries\v7.1\System.Runtime.WindowsRuntime.UI.Xaml.exe", but it didn't exist.
          For SearchPath "{WinMDFoldersEx:Software\Microsoft\Microsoft SDKs\Windows Phone,8.0}".
          Considered "{WinMDFoldersEx:Software\Microsoft\Microsoft SDKs\Windows Phone,8.0}\System.Runtime.WindowsRuntime.UI.Xaml.winmd", but it didn't exist.
          Considered "{WinMDFoldersEx:Software\Microsoft\Microsoft SDKs\Windows Phone,8.0}\System.Runtime.WindowsRuntime.UI.Xaml.dll", but it didn't exist.
          Considered "{WinMDFoldersEx:Software\Microsoft\Microsoft SDKs\Windows Phone,8.0}\System.Runtime.WindowsRuntime.UI.Xaml.exe", but it didn't exist.
          For SearchPath "Bin\Release\".
          Considered "Bin\Release\System.Runtime.WindowsRuntime.UI.Xaml.winmd", but it didn't exist.
          Considered "Bin\Release\System.Runtime.WindowsRuntime.UI.Xaml.dll", but it didn't exist.
          Considered "Bin\Release\System.Runtime.WindowsRuntime.UI.Xaml.exe", but it didn't exist.
      Required by "BarcodeLib".
  There was a conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e".
      "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" was chosen because it had a higher version.
      References which depend on "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" [].
          C:\project\Plugins\com.manateeworks.barcodescanner\BarcodeLib.winmd
            Project file item includes which caused reference "C:\project\Plugins\com.manateeworks.barcodescanner\BarcodeLib.winmd".
              BarcodeLib
      References which depend on "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\WindowsPhone\v8.0\mscorlib.dll].
          C:\project\plugins\com.phonegap.plugins.PushPlugin\Newtonsoft.Json.dll
            Project file item includes which caused reference "C:\project\plugins\com.phonegap.plugins.PushPlugin\Newtonsoft.Json.dll".
              Newtonsoft.Json
          C:\project\Plugins\com.manateeworks.barcodescanner\WriteableBitmapExWinPhone.dll
            Project file item includes which caused reference "C:\project\Plugins\com.manateeworks.barcodescanner\WriteableBitmapExWinPhone.dll".
              WriteableBitmapExWinPhone
          C:\project\plugins\com.phonegap.plugins.barcodescanner\zxing.wp8.0.dll
            Project file item includes which caused reference "C:\project\plugins\com.phonegap.plugins.barcodescanner\zxing.wp8.0.dll".
              zxing.wp8.0
Done executing task "ResolveAssemblyReference" -- FAILED.
Done building target "ResolveAssemblyReferences" in project "SingleID.csproj" -- FAILED.
Target "_CheckForCompileOutputs" in file "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets" from project "C:\project\SingleID.csproj" (target "_CleanGetCurrentAndPriorFileWrites" depends on it):
Done building target "_CheckForCompileOutputs" in project "SingleID.csproj".
Target "_SGenCheckForOutputs" skipped, due to false condition; ('$(_SGenGenerateSerializationAssembliesConfig)' == 'On' or ('@(WebReferenceUrl)'!='' and '$(_SGenGenerateSerializationAssembliesConfig)' == 'Auto')) was evaluated as ('Auto' == 'On' or (''!='' and 'Auto' == 'Auto')).
Target "_CleanGetCurrentAndPriorFileWrites" in file "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets" from project "C:\project\SingleID.csproj" (target "_CleanRecordFileWrites" depends on it):
Task "ReadLinesFromFile"
Done executing task "ReadLinesFromFile".
Using "ConvertToAbsolutePath" task from assembly "Microsoft.Build.Tasks.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
Task "ConvertToAbsolutePath"
Done executing task "ConvertToAbsolutePath".
Task "FindUnderPath"
  Comparison path is "C:\project".
Done executing task "FindUnderPath".
Task "FindUnderPath"
  Comparison path is "Bin\Release\".
Done executing task "FindUnderPath".
Task "FindUnderPath"
  Comparison path is "obj\Release\".
Done executing task "FindUnderPath".
Task "RemoveDuplicates"
Done executing task "RemoveDuplicates".
Done building target "_CleanGetCurrentAndPriorFileWrites" in project "SingleID.csproj".
Target "_CleanRecordFileWrites" in file "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets" from project "C:\project\SingleID.csproj" (target "CoreBuild" depends on it):
Task "RemoveDuplicates"
Done executing task "RemoveDuplicates".
Task "MakeDir"
Done executing task "MakeDir".
Task "WriteLinesToFile"
Done executing task "WriteLinesToFile".
Done building target "_CleanRecordFileWrites" in project "SingleID.csproj".
Done Building Project "C:\project\SingleID.csproj" (Rebuild target(s)) -- FAILED.
Done executing task "MSBuild" -- FAILED.
Done building target "Rebuild" in project "SingleID.sln" -- FAILED.
Done Building Project "C:\project\SingleID.sln" (Rebuild target(s)) -- FAILED.

Build FAILED.

**Comment by manateeworks** [comment]
Can you please write exact steps you are using to add the plugin?

**Comment by SingleID** [comment]
It's so simple that is really hard to make an error :-)

I add this line in the config.xml

`<gap:plugin name="com.manateeworks.barcodescanner" />`

The I add this code

`<form style="width: 100%; text-align: center;">
					<input type="button" value="Scan Barcode" onclick="scanner.startScanning()" style="font-size: 40px; width: 300px; height: 50px; margin-top: 100px;"/>
				</form>`


Then I zip all and send to Phonegap Build


the iOs building is done and working well
the Android build is done and working well

The WindowsPhone 8 build fail
( here is the entire log https://dl.dropboxusercontent.com/u/10636650/build.fail.log )



thank you

**Comment by manateeworks** [comment]
Sorry, i didn't realized you are using online builder.

We just updated the plugin to the latest version on build.phonegap.com (to 1.5.0), but it still return error about CPU architecture mismatch. Unfortunately, we are not able to solve it currently because our decoder library is C++ DLL, and it can't be build for 'Any CPU' configuration which is selected by default in new phonegap project. If you load such project to VS, it's building without issues, but not with the MSBuild version used on build.phonegap.com.

We will keep investigating this issue and release an update if we find a solution for online builder and wp8.

Regards

**Comment by SingleID** [comment]
I have written a support request in the community forum of Phonegap Build ( http://community.phonegap.com/nitobi/topics/barcode-plugin-bloxlab-fail )

Best Regards

**Comment by manateeworks** [comment]
We saw your post yesterday, hope they will provide some useful answer.

Thank you

**Comment by manateeworks** [comment]
Sorry for the delay. This matter has been resolved.
